{
 "title": "NB-HomeAutomation-BlogEdition",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Home Thermostat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Outside Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nbu0x2dpi4u0x2dha_sensor_temperature_celsius{domain=\"sensor\", entity=\"sensor.home_realfeel_temperature\", friendly_name=\"Home RealFeel temperature\", instance=\"localhost:8123\", job=\"nb-pi4-ha\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Home Thermostat Mode",
   "type": "stat",
   "description": "NB Ecobee home thermostat current mode",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Ecobee Thermostat\", mode=~\"cool|heat|heat_cool|off\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Living Room Current Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "{__name__=\"nbu0x2dpi4u0x2dha_climate_current_temperature_celsius\"}",
     "legendFormat": "Current Temp"
    }
   ]
  },
  {
   "title": "Living Room Occupancy Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=~\"My ecobee Occupancy\", __name__=\"nbu0x2dpi4u0x2dha_binary_sensor_state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity Percentage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"nbu0x2dpi4u0x2dha_sensor_humidity_percent\"}",
     "legendFormat": "Humidity %"
    }
   ]
  },
  {
   "title": "HVAC Fan Status",
   "type": "stat",
   "description": "Is the fan on or off?",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", action=\"fan\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "title": "Home Security System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Home Security System Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=~\"Milton Siren\", __name__=\"nbu0x2dpi4u0x2dha_switch_state\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Base Station Wi-Fi Signal Strength",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=~\"Milton Base Station Wireless\", __name__=\"nbu0x2dpi4u0x2dha_sensor_signal_strength_dbm\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Front Door Bell Volume",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Front Door Volume\", __name__=\"nbu0x2dpi4u0x2dha_sensor_state\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Front Door Bell",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Front Door Ding\", entity=\"binary_sensor.front_door_ding_2\", __name__=\"nbu0x2dpi4u0x2dha_binary_sensor_state\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Front Door Last Activity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()- {job=\"nb-pi4-ha\", friendly_name=\"Front Door Last Motion\", __name__=\"nbu0x2dpi4u0x2dha_last_updated_time_seconds\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Front Door Bell Wi-Fi Signal Strength",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nbu0x2dpi4u0x2dha_sensor_signal_strength_dbm{domain=\"sensor\", entity=\"sensor.front_door_wireless\", friendly_name=\"Front Door Wireless\", instance=\"localhost:8123\", job=\"nb-pi4-ha\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Garage Door",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Garage Door\", __name__=\"nbu0x2dpi4u0x2dha_binary_sensor_state\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Garage Home Entrance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Garage Home Entrance\", __name__=\"nbu0x2dpi4u0x2dha_binary_sensor_state\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Front Door",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Front Door\", __name__=\"nbu0x2dpi4u0x2dha_binary_sensor_state\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Living Room Sliding Door",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Main Room Sliding Door\", __name__=\"nbu0x2dpi4u0x2dha_binary_sensor_state\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Hallway Motion Sensor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Entry Hallway Motion Sensor\", __name__=\"nbu0x2dpi4u0x2dha_binary_sensor_state\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Keypad",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Ring Keypad Tamper\", __name__=\"nbu0x2dpi4u0x2dha_binary_sensor_state\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Basement Access Door",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Main Room Sliding Door\", __name__=\"nbu0x2dpi4u0x2dha_binary_sensor_state\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Upstairs Motion Sensor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Upstairs Hallway Motion Sensor\", __name__=\"nbu0x2dpi4u0x2dha_binary_sensor_state\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Garage Door Battery",
   "type": "stat",
   "description": "Battery Percentage",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=~\"Garage Door Battery\", __name__=\"nbu0x2dpi4u0x2dha_sensor_battery_percent\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Garage Home Entrance Battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=~\"Garage Home Entrance Battery\", __name__=\"nbu0x2dpi4u0x2dha_sensor_battery_percent\"}",
     "legendFormat": "{{frindly_name}}"
    }
   ]
  },
  {
   "title": "Front Door Battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=~\"Front Door Battery\", __name__=\"nbu0x2dpi4u0x2dha_sensor_battery_percent\"}",
     "legendFormat": "{{frindly_name}}"
    }
   ]
  },
  {
   "title": "Living Room Sliding Door Battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Main Room Sliding Door Battery\", __name__=\"nbu0x2dpi4u0x2dha_sensor_battery_percent\"}",
     "legendFormat": "{{frindly_name}}"
    }
   ]
  },
  {
   "title": "Hallway Motion Sensor Battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Entry Hallway Motion Sensor Battery\", __name__=\"nbu0x2dpi4u0x2dha_sensor_battery_percent\"}",
     "legendFormat": "{{frindly_name}}"
    }
   ]
  },
  {
   "title": "Keypad Battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Ring Keypad Battery\", __name__=\"nbu0x2dpi4u0x2dha_sensor_battery_percent\"}",
     "legendFormat": "{{frindly_name}}"
    }
   ]
  },
  {
   "title": "Basement Access Door Battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"nb-pi4-ha\", friendly_name=~\"Front Door Battery\", __name__=\"nbu0x2dpi4u0x2dha_sensor_battery_percent\"}",
     "legendFormat": "{{frindly_name}}"
    }
   ]
  },
  {
   "title": "Upstairs Motion Sensor Battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nbu0x2dpi4u0x2dha_sensor_battery_percent{domain=\"sensor\", entity=\"sensor.upstairs_hallway_motion_sensor_battery\", friendly_name=\"Upstairs Hallway Motion Sensor Battery\", instance=\"localhost:8123\", job=\"nb-pi4-ha\"}",
     "legendFormat": "{{frindly_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Smart Devices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Samsung TV",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{job=\"nb-pi4-ha\", friendly_name=~\"Wemo Plug 1\", __name__=\"nbu0x2dpi4u0x2dha_switch_state\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Samsung TV Energy Consumption",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 2, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "expr": "last_over_time({job=\"nb-pi4-ha\", friendly_name=~\"Wemo Plug 1 Today Energy\", __name__=\"nbu0x2dpi4u0x2dha_sensor_energy_kwh\"}[$__range])",
       "legendFormat": "Current Temp"
      }
     ]
    },
    {
     "title": "Samsung TV Daily Electricity Cost",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_over_time({job=\"nb-pi4-ha\", friendly_name=~\"Wemo Plug 1 Today Energy\", __name__=\"nbu0x2dpi4u0x2dha_sensor_energy_kwh\"}[$__range]) * 9.5",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LG TV",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 12, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{job=\"nb-pi4-ha\", friendly_name=~\"Wemo Plug 2\", __name__=\"nbu0x2dpi4u0x2dha_switch_state\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LG TV Energy Consumption",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "expr": "last_over_time({job=\"nb-pi4-ha\", friendly_name=~\"Wemo Plug 2 Today Energy\", __name__=\"nbu0x2dpi4u0x2dha_sensor_energy_kwh\"}[$__range])",
       "legendFormat": "Current Temp"
      }
     ]
    },
    {
     "title": "LG TV Daily Electricity Cost",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_over_time({job=\"nb-pi4-ha\", friendly_name=~\"Wemo Plug 2 Today Energy\", __name__=\"nbu0x2dpi4u0x2dha_sensor_energy_kwh\"}[$__range]) * 9.5",
       "legendFormat": "__auto"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } }
   ]
  },
  {
   "title": "Home Office",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "HP Printer Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{job=\"nb-pi4-ha\", friendly_name=\"HP ENVY 4520 series\", __name__=\"nbu0x2dpi4u0x2dha_entity_available\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HP Printer | Black Cartridge Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 2, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{job=\"nb-pi4-ha\", friendly_name=\"HP ENVY 4520 series black ink\", __name__=\"nbu0x2dpi4u0x2dha_sensor_unit_percent\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HP Printer | Color Cartridge Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 5, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{job=\"nb-pi4-ha\", __name__=\"nbu0x2dpi4u0x2dha_sensor_unit_percent\", friendly_name=\"HP ENVY 4520 series tri-color ink\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 6, "w": 1, "x": 8, "y": 29 } },
    {
     "title": "Work Macbook Power Supply State",
     "type": "stat",
     "description": "Power Mode",
     "gridPos": { "h": 6, "w": 6, "x": 9, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{job=\"nb-mac\", state=~\"AC Power|Battery Power|Off Line\", __name__=\"node_power_supply_power_source_state\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Macbook Battery Percentage",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{job=\"nb-mac\", __name__=\"node_power_supply_current_capacity\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_memory_active_bytes{job=~\"nb-mac\"} * 100) / node_memory_total_bytes{job=~\"nb-mac\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{job=~\"nb-mac\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"nb-mac\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{job=~\"nb-mac\"}) by (cpu))",
       "legendFormat": "__auto"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } }
   ]
  },
  {
   "title": "Home Router",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Router Status",
     "type": "stat",
     "description": "Router Status",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{job=\"nb-pi4-ha\", friendly_name=\"Home Router Data Received\", __name__=\"nbu0x2dpi4u0x2dha_entity_available\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Packets Sent/Received",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 8, "x": 6, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{__name__=\"nbu0x2dpi4u0x2dha_sensor_unit_packets\"}",
       "legendFormat": "{{friendly_name}}"
      }
     ]
    },
    {
     "title": "Router Traffic Volume",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "{job=\"nb-pi4-ha\", friendly_name=~\"Home.*\", friendly_name=\"Home Router Data Received\", __name__=\"nbu0x2dpi4u0x2dha_sensor_unit_kib_per_s\"}",
       "legendFormat": "Data Received"
      },
      {
       "expr": "{job=\"nb-pi4-ha\", friendly_name=~\"Home.*\", friendly_name=\"Home Router Data Sent\", __name__=\"nbu0x2dpi4u0x2dha_sensor_unit_kib_per_s\"}",
       "legendFormat": "Data Sent"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } }
   ]
  }
 ]
}